/**
 * Notification title humaniser.
 *
 * Notification titles are generated by services in mixed English phrasing
 * (e.g. "OUT-OF-SPEC env inspection on room #5", "Scale TEQ-2 FAILED
 * verification"). Translate the common fixed phrases to Thai for readability —
 * DISPLAY ONLY, the stored value is untouched. Unknown text passes through.
 *
 * Shared by the maintenance notifications page and the top-nav notification
 * bell so both render the same Thai text.
 */
const MAP: Array<[RegExp, string]> = [
  [/OUT-OF-SPEC\s+env(ironmental)?\s+inspection\s+on\s+/gi, 'ตรวจสภาพแวดล้อมเกินเกณฑ์ที่ '],
  [/Environmental\s+inspection\s+OVERDUE\s*—?\s*/gi, 'ตรวจสภาพแวดล้อมเกินกำหนด — '],
  [/Water\s+quality\s+OUT-OF-SPEC\s+on\s+/gi, 'คุณภาพน้ำเกินเกณฑ์ที่ '],
  [/Water\s+test\s+OVERDUE\s*—?\s*/gi, 'ตรวจคุณภาพน้ำเกินกำหนด — '],
  [/Scale\s+(.+?)\s+FAILED\s+verification/gi, 'เครื่องชั่ง $1 ตรวจสอบไม่ผ่าน'],
  [/calibration\s+due/gi, 'ถึงกำหนดสอบเทียบ'],
  [/calibration\s+overdue/gi, 'เกินกำหนดสอบเทียบ'],
  [/maintenance\s+due/gi, 'ถึงกำหนดบำรุงรักษา'],
  [/inspection\s+due/gi, 'ถึงกำหนดตรวจสอบ'],
  [/\bstorage_area\b/gi, 'พื้นที่จัดเก็บ'],
  [/\broom\b/gi, 'ห้อง'],
];

export function friendlyNotificationTitle(raw: string): string {
  if (!raw) return raw;
  let s = raw;
  for (const [re, th] of MAP) s = s.replace(re, th);
  return s;
}
