/**
 * Lot Number Pattern — validation schemas.
 *
 * Two scopes: 'system' (lot generated by clicking "สร้าง") and 'vendor'
 * (input rules / hint for vendor-supplied lot numbers).
 */
import { z } from 'zod';

export const PATTERN_TYPES = ['system', 'vendor'] as const;
export const DATE_FORMATS = ['YYYYMMDD', 'YYMMDD', 'BE-YYMMDD', 'BE-YYYYMMDD', 'YYYY-MM-DD', 'none'] as const;
export const SEQUENCE_TYPES = ['random', 'sequential'] as const;
export const SEPARATORS = ['-', '_', '/', '.', ''] as const;

export type LotPatternType = typeof PATTERN_TYPES[number];
export type LotDateFormat = typeof DATE_FORMATS[number];
export type LotSequenceType = typeof SEQUENCE_TYPES[number];

export const lotPatternSchema = z.object({
  patternType: z.enum(PATTERN_TYPES),
  prefix: z.string().trim().max(20).default('LOT'),
  separator: z.string().max(5).default('-'),
  includeDate: z.boolean().default(true),
  dateFormat: z.enum(DATE_FORMATS).default('YYYYMMDD'),
  sequenceType: z.enum(SEQUENCE_TYPES).default('random'),
  sequenceLength: z.number().int().min(1).max(8).default(3),
  sequenceStart: z.number().int().min(1).default(1),
  regexPattern: z.string().max(200).optional().nullable(),
  hintTh: z.string().max(200).optional().nullable(),
  hintEn: z.string().max(200).optional().nullable(),
  isActive: z.boolean().default(true),
  notes: z.string().max(500).optional().nullable(),
});

export type LotPatternInput = z.infer<typeof lotPatternSchema>;

export const DEFAULT_SYSTEM_PATTERN: Omit<LotPatternInput, 'patternType'> = {
  prefix: 'LOT',
  separator: '-',
  includeDate: true,
  dateFormat: 'YYYYMMDD',
  sequenceType: 'random',
  sequenceLength: 3,
  sequenceStart: 1,
  regexPattern: null,
  hintTh: null,
  hintEn: null,
  isActive: true,
  notes: null,
};

export const DEFAULT_VENDOR_PATTERN: Omit<LotPatternInput, 'patternType'> = {
  prefix: '',
  separator: '-',
  includeDate: false,
  dateFormat: 'none',
  sequenceType: 'random',
  sequenceLength: 3,
  sequenceStart: 1,
  regexPattern: null, // null = no validation (accept anything)
  hintTh: 'เลข Lot ผู้ขาย',
  hintEn: 'Vendor Lot Number',
  isActive: true,
  notes: null,
};
