'use client';

/**
 * VMI Webhook Configuration Form Component
 *
 * Form for creating and editing webhook configurations.
 * Includes event selection, URL display, and secret management.
 *
 * Feature: 012-vmi-webhook
 */

import * as React from 'react';
import { DxButton } from '@/components/ui/dx-button';
import { DxTextBox } from '@/components/ui/dx-text-box';
import { DxCheckBox } from '@/components/ui/dx-check-box';
import { DxTextArea } from '@/components/ui/dx-text-area';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils/cn';
import {
  Webhook,
  Bell,
  Key,
  Copy,
  Check,
  AlertTriangle,
  ShoppingCart,
  XCircle,
  Package,
  CheckCircle2,
  Eye,
  EyeOff,
  RefreshCw,
  Loader2,
  Save,
} from 'lucide-react';
import type {
  VmiWebhookEventType,
  VmiWebhookCreate,
  VmiWebhookUpdate,
} from '@/types/vmi';

// ============================================================================
// Types
// ============================================================================

export interface WebhookConfigFormProps {
  portalId: number;
  portalName: string;
  mode: 'create' | 'edit';
  /** Webhook URL (read-only, generated by system) */
  webhookUrl?: string;
  /** Initial values for edit mode */
  initialValues?: {
    id: number;
    name: string;
    description?: string | null;
    events: VmiWebhookEventType[];
    isActive: boolean;
  };
  /** Secret returned after create (display once) */
  secret?: string;
  onSubmit: (data: VmiWebhookCreate | VmiWebhookUpdate) => Promise<void>;
  onRegenerateSecret?: () => Promise<void>;
  onCancel: () => void;
  isSubmitting?: boolean;
  isRegenerating?: boolean;
  className?: string;
}

interface EventOption {
  value: VmiWebhookEventType;
  label: string;
  labelTh: string;
  description: string;
  icon: typeof ShoppingCart;
  color: string;
}

// ============================================================================
// Constants
// ============================================================================

const EVENT_OPTIONS: EventOption[] = [
  {
    value: 'order.created',
    label: 'Order Created',
    labelTh: 'สร้างคำสั่งซื้อ',
    description: 'Triggered when a hospital submits a new order',
    icon: ShoppingCart,
    color: 'text-blue-600 bg-blue-50',
  },
  {
    value: 'order.cancelled',
    label: 'Order Cancelled',
    labelTh: 'ยกเลิกคำสั่งซื้อ',
    description: 'Triggered when a hospital cancels an order',
    icon: XCircle,
    color: 'text-red-600 bg-red-50',
  },
  {
    value: 'receipt.created',
    label: 'Receipt Created',
    labelTh: 'สร้างใบรับสินค้า',
    description: 'Triggered when goods are received (partial)',
    icon: Package,
    color: 'text-amber-600 bg-amber-50',
  },
  {
    value: 'receipt.completed',
    label: 'Receipt Completed',
    labelTh: 'รับสินค้าครบ',
    description: 'Triggered when all goods are received',
    icon: CheckCircle2,
    color: 'text-green-600 bg-green-50',
  },
];

// ============================================================================
// Section Card Component
// ============================================================================

interface SectionCardProps {
  icon: React.ReactNode;
  title: string;
  description?: string;
  children: React.ReactNode;
  className?: string;
  variant?: 'default' | 'highlight' | 'warning' | 'success';
}

function SectionCard({
  icon,
  title,
  description,
  children,
  className,
  variant = 'default',
}: SectionCardProps) {
  const variants = {
    default: {
      border: 'border-gray-200',
      bg: 'bg-white',
      headerBg: 'bg-gray-50/50',
      headerBorder: 'border-gray-100',
      iconBg: 'bg-white border border-gray-200',
    },
    highlight: {
      border: 'border-blue-200',
      bg: 'bg-gradient-to-br from-blue-50/50 to-white',
      headerBg: 'bg-blue-50/50',
      headerBorder: 'border-blue-100',
      iconBg: 'bg-blue-100',
    },
    warning: {
      border: 'border-amber-200',
      bg: 'bg-gradient-to-br from-amber-50/50 to-white',
      headerBg: 'bg-amber-50/50',
      headerBorder: 'border-amber-100',
      iconBg: 'bg-amber-100',
    },
    success: {
      border: 'border-emerald-200',
      bg: 'bg-gradient-to-br from-emerald-50/50 to-white',
      headerBg: 'bg-emerald-50/50',
      headerBorder: 'border-emerald-100',
      iconBg: 'bg-emerald-100',
    },
  };

  const v = variants[variant];

  return (
    <div className={cn('rounded-2xl border overflow-hidden', v.border, v.bg, className)}>
      <div className={cn('px-5 py-4 border-b flex items-center gap-3', v.headerBorder, v.headerBg)}>
        <div className={cn('p-2.5 rounded-xl', v.iconBg)}>{icon}</div>
        <div className="flex-1 min-w-0">
          <h3 className="text-sm font-semibold text-gray-900">{title}</h3>
          {description && <p className="text-xs text-gray-500 mt-0.5">{description}</p>}
        </div>
      </div>
      <div className="p-5">{children}</div>
    </div>
  );
}

// ============================================================================
// Secret Display Component
// ============================================================================

interface SecretDisplayProps {
  secret: string;
  onClose?: () => void;
}

function SecretDisplay({ secret }: SecretDisplayProps) {
  const [copied, setCopied] = React.useState(false);
  const [showSecret, setShowSecret] = React.useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(secret);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="p-4 rounded-xl bg-amber-50 border border-amber-200">
      <div className="flex items-start gap-3 mb-3">
        <AlertTriangle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
        <div>
          <p className="font-semibold text-amber-800">Save this secret now!</p>
          <p className="text-sm text-amber-700 mt-1">
            This secret will only be shown once. Copy it and store it securely.
            You will need it to verify webhook signatures.
          </p>
        </div>
      </div>

      <div className="flex items-center gap-2 mt-4">
        <div className="flex-1 font-mono text-sm bg-white border border-amber-300 rounded-lg px-3 py-2 overflow-hidden">
          {showSecret ? secret : '••••••••••••••••••••••••••••••••'}
        </div>
        <DxButton
          icon={showSecret ? 'eyeopen' : 'eyeclose'}
          type="normal"
          stylingMode="outlined"
          onClick={() => setShowSecret(!showSecret)}
          hint={showSecret ? 'Hide secret' : 'Show secret'}
        />
        <DxButton
          icon={copied ? 'check' : 'copy'}
          type={copied ? 'success' : 'default'}
          stylingMode="contained"
          onClick={handleCopy}
          hint={copied ? 'Copied!' : 'Copy to clipboard'}
        />
      </div>
    </div>
  );
}

// ============================================================================
// Main Form Component
// ============================================================================

export function WebhookConfigForm({
  portalId,
  portalName,
  mode,
  webhookUrl,
  initialValues,
  secret,
  onSubmit,
  onRegenerateSecret,
  onCancel,
  isSubmitting = false,
  isRegenerating = false,
  className,
}: WebhookConfigFormProps) {
  const [formData, setFormData] = React.useState({
    name: initialValues?.name || '',
    description: initialValues?.description || '',
    events: initialValues?.events || [] as VmiWebhookEventType[],
    isActive: initialValues?.isActive ?? true,
  });

  const [urlCopied, setUrlCopied] = React.useState(false);

  const handleCopyUrl = async () => {
    if (webhookUrl) {
      await navigator.clipboard.writeText(webhookUrl);
      setUrlCopied(true);
      setTimeout(() => setUrlCopied(false), 2000);
    }
  };

  const toggleEvent = (event: VmiWebhookEventType) => {
    setFormData((prev) => ({
      ...prev,
      events: prev.events.includes(event)
        ? prev.events.filter((e) => e !== event)
        : [...prev.events, event],
    }));
  };

  const selectAllEvents = () => {
    setFormData((prev) => ({
      ...prev,
      events: EVENT_OPTIONS.map((e) => e.value),
    }));
  };

  const clearAllEvents = () => {
    setFormData((prev) => ({
      ...prev,
      events: [],
    }));
  };

  const handleSubmit = async () => {
    if (mode === 'create') {
      const data: VmiWebhookCreate = {
        name: formData.name,
        description: formData.description || undefined,
        events: formData.events,
      };
      await onSubmit(data);
    } else {
      const data: VmiWebhookUpdate = {
        name: formData.name,
        description: formData.description || undefined,
        events: formData.events,
        isActive: formData.isActive,
      };
      await onSubmit(data);
    }
  };

  const isValid = formData.name.trim().length > 0 && formData.events.length > 0;

  return (
    <div className={cn('space-y-6', className)}>
      {/* Header */}
      <div
        className={cn(
          'rounded-2xl p-5 border',
          mode === 'create'
            ? 'bg-blue-50 border-blue-200'
            : 'bg-gray-50 border-gray-200'
        )}
      >
        <div className="flex items-start gap-4">
          <div
            className={cn(
              'p-3 rounded-xl',
              mode === 'create' ? 'bg-blue-100' : 'bg-gray-100'
            )}
          >
            <Webhook
              className={cn(
                'h-6 w-6',
                mode === 'create' ? 'text-blue-600' : 'text-gray-600'
              )}
            />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-gray-900">
              {mode === 'create' ? 'Create New Webhook' : 'Edit Webhook'}
            </h3>
            <p className="text-sm text-gray-600 mt-1">
              {mode === 'create'
                ? `Configure a webhook to receive real-time notifications from ${portalName}`
                : `Update webhook configuration for ${portalName}`}
            </p>
          </div>
        </div>
      </div>

      {/* Secret Display (after create) */}
      {secret && <SecretDisplay secret={secret} />}

      <div className="grid grid-cols-12 gap-6">
        {/* Left Column - Basic Info & Events */}
        <div className="col-span-7 space-y-6">
          {/* Basic Information */}
          <SectionCard
            icon={<Webhook className="h-5 w-5 text-gray-600" />}
            title="Basic Information"
            description="Webhook name and description"
          >
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Webhook Name <span className="text-red-500">*</span>
                </label>
                <DxTextBox
                  value={formData.name}
                  onValueChange={(value) =>
                    setFormData((prev) => ({ ...prev, name: value }))
                  }
                  placeholder="e.g., Production Webhook"
                  maxLength={100}
                />
                <p className="text-xs text-gray-500 mt-1">
                  A descriptive name to identify this webhook
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Description
                </label>
                <DxTextArea
                  value={formData.description}
                  onValueChange={(value) =>
                    setFormData((prev) => ({ ...prev, description: value }))
                  }
                  placeholder="Optional description..."
                  maxLength={500}
                  height={80}
                />
              </div>

              {mode === 'edit' && (
                <div className="pt-2 border-t">
                  <label className="flex items-center gap-3 cursor-pointer">
                    <DxCheckBox
                      value={formData.isActive}
                      onValueChange={(value) =>
                        setFormData((prev) => ({ ...prev, isActive: value ?? true }))
                      }
                    />
                    <div>
                      <span className="text-sm font-medium text-gray-900">Active</span>
                      <p className="text-xs text-gray-500">
                        Enable or disable this webhook
                      </p>
                    </div>
                  </label>
                </div>
              )}
            </div>
          </SectionCard>

          {/* Event Selection */}
          <SectionCard
            icon={<Bell className="h-5 w-5 text-gray-600" />}
            title="Event Subscriptions"
            description="Select which events to receive"
            variant={formData.events.length > 0 ? 'success' : 'warning'}
          >
            <div className="space-y-4">
              {/* Quick Actions */}
              <div className="flex items-center justify-between pb-3 border-b">
                <span className="text-sm text-gray-500">
                  {formData.events.length} of {EVENT_OPTIONS.length} events selected
                </span>
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={selectAllEvents}
                    className="text-xs text-blue-600 hover:text-blue-800"
                  >
                    Select All
                  </button>
                  <span className="text-gray-300">|</span>
                  <button
                    type="button"
                    onClick={clearAllEvents}
                    className="text-xs text-gray-500 hover:text-gray-700"
                  >
                    Clear All
                  </button>
                </div>
              </div>

              {/* Event Options */}
              <div className="grid grid-cols-2 gap-3">
                {EVENT_OPTIONS.map((event) => {
                  const Icon = event.icon;
                  const isSelected = formData.events.includes(event.value);
                  return (
                    <label
                      key={event.value}
                      className={cn(
                        'flex items-start gap-3 p-4 rounded-xl border-2 cursor-pointer transition-all',
                        isSelected
                          ? 'border-blue-400 bg-blue-50 shadow-sm'
                          : 'border-gray-200 hover:border-gray-300'
                      )}
                    >
                      <DxCheckBox
                        value={isSelected}
                        onValueChange={() => toggleEvent(event.value)}
                      />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <div className={cn('p-1.5 rounded-lg', event.color)}>
                            <Icon className="h-4 w-4" />
                          </div>
                          <span className="text-sm font-medium text-gray-900">
                            {event.labelTh}
                          </span>
                        </div>
                        <p className="text-xs text-gray-500 mt-1 line-clamp-2">
                          {event.description}
                        </p>
                        <code className="text-[10px] text-gray-400 mt-1 block">
                          {event.value}
                        </code>
                      </div>
                    </label>
                  );
                })}
              </div>

              {formData.events.length === 0 && (
                <p className="text-sm text-amber-600 flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4" />
                  Please select at least one event to subscribe to
                </p>
              )}
            </div>
          </SectionCard>
        </div>

        {/* Right Column - URL & Secret */}
        <div className="col-span-5 space-y-6">
          {/* Webhook URL */}
          {webhookUrl && (
            <SectionCard
              icon={<Webhook className="h-5 w-5 text-gray-600" />}
              title="Webhook URL"
              description="Configure this URL in VMI Portal"
              variant="highlight"
            >
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <div className="flex-1 font-mono text-xs bg-gray-100 border rounded-lg px-3 py-2 overflow-x-auto whitespace-nowrap">
                    {webhookUrl}
                  </div>
                  <DxButton
                    icon={urlCopied ? 'check' : 'copy'}
                    type={urlCopied ? 'success' : 'normal'}
                    stylingMode="outlined"
                    onClick={handleCopyUrl}
                    hint={urlCopied ? 'Copied!' : 'Copy URL'}
                  />
                </div>
                <p className="text-xs text-gray-500">
                  Register this URL in your VMI Portal's webhook configuration.
                </p>
              </div>
            </SectionCard>
          )}

          {/* Secret Management (edit mode) */}
          {mode === 'edit' && onRegenerateSecret && (
            <SectionCard
              icon={<Key className="h-5 w-5 text-gray-600" />}
              title="Webhook Secret"
              description="Used to verify webhook signatures"
            >
              <div className="space-y-4">
                <div className="p-3 bg-gray-50 rounded-lg">
                  <p className="text-sm text-gray-600">
                    The webhook secret is encrypted and cannot be displayed.
                    If you've lost it, you can regenerate a new one.
                  </p>
                </div>

                <DxButton
                  text={isRegenerating ? 'Regenerating...' : 'Regenerate Secret'}
                  icon={isRegenerating ? undefined : 'refresh'}
                  type="danger"
                  stylingMode="outlined"
                  width="100%"
                  onClick={onRegenerateSecret}
                  disabled={isRegenerating}
                >
                  {isRegenerating && (
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  )}
                </DxButton>

                <p className="text-xs text-amber-600 flex items-start gap-2">
                  <AlertTriangle className="h-4 w-4 flex-shrink-0 mt-0.5" />
                  <span>
                    Warning: Regenerating the secret will invalidate the current
                    one. Update your VMI Portal configuration immediately.
                  </span>
                </p>
              </div>
            </SectionCard>
          )}

          {/* Integration Guide */}
          <SectionCard
            icon={<Package className="h-5 w-5 text-gray-600" />}
            title="Integration Guide"
            description="Steps to configure VMI Portal"
          >
            <ol className="space-y-3 text-sm">
              <li className="flex gap-3">
                <span className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center text-xs font-bold text-blue-600">
                  1
                </span>
                <span className="text-gray-600">
                  Copy the webhook URL above
                </span>
              </li>
              <li className="flex gap-3">
                <span className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center text-xs font-bold text-blue-600">
                  2
                </span>
                <span className="text-gray-600">
                  Log into VMI Portal and navigate to API settings
                </span>
              </li>
              <li className="flex gap-3">
                <span className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center text-xs font-bold text-blue-600">
                  3
                </span>
                <span className="text-gray-600">
                  Register a new webhook with the URL and secret
                </span>
              </li>
              <li className="flex gap-3">
                <span className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center text-xs font-bold text-blue-600">
                  4
                </span>
                <span className="text-gray-600">
                  Select the events matching your subscription
                </span>
              </li>
            </ol>
          </SectionCard>

          {/* Action Buttons */}
          <div className="space-y-3 sticky bottom-0 pt-4">
            <DxButton
              text={
                isSubmitting
                  ? 'Saving...'
                  : mode === 'create'
                    ? 'Create Webhook'
                    : 'Save Changes'
              }
              icon="save"
              type="success"
              stylingMode="contained"
              width="100%"
              onClick={handleSubmit}
              disabled={isSubmitting || !isValid}
            />
            <DxButton
              text="Cancel"
              type="normal"
              stylingMode="outlined"
              width="100%"
              onClick={onCancel}
              disabled={isSubmitting}
            />
            {!isValid && (
              <p className="text-xs text-amber-600 text-center">
                Please fill in all required fields
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default WebhookConfigForm;
